name: 'Setup blogc environment'
description: 'Setup a blogc environment and add it to the PATH'

inputs:
  blogc-version:
    description: 'The blogc version to setup. Must be a git reference or LATEST for latest stable release'
    required: true
    default: 'LATEST'

outputs:
  blogc-version:
    description: 'The installed blogc version. Useful when given LATEST as input.'
  cache-hit:
    description: 'A boolean value to indicate if a cache was hit'

runs:
  using: "composite"
  steps:
    - name: Check runner OS
      if: ${{ runner.os != 'Linux' }}
      run: |
        echo "::error title=Error hint::The setup-blogc action supports only linux"
        exit 1
      shell: bash

    - name: Restore blogc build from cache, if exists
      id: cache-restore
      uses: actions/cache/restore@v3
      with:
        path: /opt/blogc
        key: Linux-build-blogc-{{ inputs.blogc-version }}

    - name: Check out code
      if: steps.cache-restore.outputs.cache-hit != 'true'
      uses: actions/checkout@v3
      with:
        repository: blogc/blogc
        ref: ${{ inputs.blogc-version }}

    - name: Install dependencies
      if: steps.cache-restore.outputs.cache-hit != 'true'
      run: sudo apt install -y ronn
      shell: bash

    - name: Build blogc
      if: steps.cache-restore.outputs.cache-hit != 'true'
      run: |
        ./autogen.sh
        ./configure \
          "CFLAGS=-Wall -g -O3" \
          --prefix=/ \
          --disable-silent-rules \
          --disable-valgrind \
          --disable-tests \
          --enable-make
        make -j4
        sudo make DESTDIR=/opt/blogc install
      shell: bash

    - name: Save blogc build to cache, if needed
      if: steps.cache-restore.outputs.cache-hit != 'true'
      uses: actions/cache/save@v3
      id: cache-save
      with:
        path: /opt/blogc
        key: Linux-build-blogc-{{ inputs.blogc-version }}

    - name: Add blogc to PATH
      run: echo "/opt/blogc/bin" >> $GITHUB_PATH
      shell: bash

    - name: Check if blogc works
      run: |
        blogc -v
        blogc-make -v
      shell: bash
