name: 'Setup blogc environment'
description: 'Setup a blogc environment and add it to the PATH'

inputs:
  blogc-version:
    description: 'The blogc version to setup. Must be a version, a Git reference or LATEST for latest stable release'
    required: true
    default: 'LATEST'

outputs:
  blogc-version:
    description: 'The installed blogc version. Useful when given LATEST as input.'

  cache-hit:
    description: 'A boolean value to indicate if a cache was hit'
    value: ${{ steps.cache-restore.outputs.cache-hit }}

runs:
  using: "composite"
  steps:
    - name: Check runner OS
      if: ${{ runner.os != 'Linux' }}
      run: |
        echo "::error title=Error hint::The setup-blogc action supports only linux"
        exit 1
      shell: bash

    - name: Resolve git reference
      id: gitref
      run: |
        ref="${{ inputs.blogc-version }}"

        if [[ "x${ref}" = xLATEST ]]; then
          ref="$(
            git \
              -c versionsort.suffix=- \
              ls-remote \
                --exit-code \
                --refs \
                --sort=version:refname \
                --tags \
                https://github.com/blogc/blogc.git \
                "v*.*.*" \
            | cut -d/ -f3- \
            | tail -n 1
          )"
        fi

        if [[ "${ref}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          ref="v${ref}"
        fi

        ref="$(git ls-remote --exit-code https://github.com/blogc/blogc.git "${ref}")"
        if [[ $? != 0 ]]; then
          echo "::error title=Error hint::The requested version was not found: ${{ inputs.blogc-version }}"
          exit 1
        fi

        echo "ref=${ref}" >> $GITHUB_OUTPUT

    - name: Restore blogc build from cache, if exists
      id: cache-restore
      uses: actions/cache/restore@v3
      with:
        path: /opt/blogc
        key: Linux-build-blogc-${{ steps.gitref.outputs.ref }}

    - name: Check out code
      if: steps.cache-restore.outputs.cache-hit != 'true'
      uses: actions/checkout@v3
      with:
        repository: blogc/blogc
        ref: ${{ steps.gitref.outputs.ref }}

    - name: Install dependencies
      if: steps.cache-restore.outputs.cache-hit != 'true'
      run: sudo apt install -y ronn
      shell: bash

    - name: Build blogc
      if: steps.cache-restore.outputs.cache-hit != 'true'
      run: |
        ./autogen.sh
        ./configure \
          "CFLAGS=-Wall -g -O3" \
          --prefix=/ \
          --disable-silent-rules \
          --disable-valgrind \
          --disable-tests \
          --enable-make
        make -j4
        sudo make DESTDIR=/opt/blogc install
      shell: bash

    - name: Save blogc build to cache, if needed
      if: steps.cache-restore.outputs.cache-hit != 'true'
      uses: actions/cache/save@v3
      id: cache-save
      with:
        path: /opt/blogc
        key: Linux-build-blogc-${{ steps.gitref.outputs.ref }}

    - name: Add blogc to PATH
      run: echo "/opt/blogc/bin" >> $GITHUB_PATH
      shell: bash

    - name: Check if blogc works
      run: |
        blogc -v
        blogc-make -v
      shell: bash
