name: Test
on:
  push:
    branches:
      - main

permissions:
  actions: write

concurrency:
  group: test
  cancel-in-progress: true

jobs:
  clear-cache:
    name: Clear cache
    runs-on: ubuntu-latest

    steps:
      - name: Clear cache
        run: gh cache delete --repo "${{ github.repository }}" --all
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test-check:
    name: Test setup-blogc
    runs-on: ubuntu-latest
    needs: clear-cache

    strategy:
      matrix:
        version:
          - HEAD
          - LATEST
          - "v0.20.0"
          - "0.19.0"
          - "3f6ae823cd8ff8049abeca2be495c727563c919e"

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Test without cache
        id: test
        uses: ./
        with:
          blogc-version: ${{ matrix.version }}

      - name: Dump outputs without cache
        run: |
          echo "Version: ${{ steps.test.outputs.blogc-version }}"
          echo "Cache hit: ${{ steps.test.outputs.cache-hit }}"

      - name: Test with cache
        id: test2
        uses: ./
        with:
          blogc-version: ${{ matrix.version }}

      - name: Dump outputs with cache
        run: |
          echo "Version: ${{ steps.test2.outputs.blogc-version }}"
          echo "Cache hit: ${{ steps.test2.outputs.cache-hit }}"
