name: Test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-check:
    name: test setup-blogc
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version:
          - HEAD
          - LATEST
          - v0.20.0
          - 0.19.0

    steps:
      - uses: actions/checkout@v3
        with:
          path: action
          clean: true

      - name: Check
        id: foo
        uses: blogc/setup-blogc@main
        with:
          blogc-version: ${{ matrix.version }}

      - name: Dump outputs
        run: |
          echo "Version: ${{ steps.foo.outputs.blogc-version }}"
          echo "Cache hit: ${{ steps.foo.outputs.cache-hit }}"
