name: Test
on:
  push:
    branches:
      - main

jobs:
  test-check:
    name: test setup-blogc
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version:
          - HEAD
          - LATEST
          - "v0.20.0"
          - "0.19.0"
          - "3f6ae823cd8ff8049abeca2be495c727563c919e"

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Test
        id: test
        uses: ./
        with:
          blogc-version: ${{ matrix.version }}

      - name: Dump outputs
        run: |
          echo "Version: ${{ steps.test.outputs.blogc-version }}"
          echo "Cache hit: ${{ steps.test.outputs.cache-hit }}"
